### ISSUE TITLE
"Empty Cache and Hard Reload" fails OidcKeepAliveServiceWorker.json request which causes strange behaviour

### ISSUE THREAD

**Issue by Zamaletdinov** [AxaFrance/react-oidc#1024]
### Issue and Steps to Reproduce
Failed "OidcKeepAliveServiceWorker.json" request causes all consequent requests to fail, even though a user seems to be "authenticated" but they aren't

### Versions
"@axa-fr/react-oidc": "^6.16.10"

### Screenshots
When I do a normal page refresh - all is good, a user is authenticated and their state is loaded :
![image](https://user-images.githubusercontent.com/8142668/229450361-bf1bc1b9-5dd7-41f8-8c1d-adf391a216a8.png)

But when I do "Empty Cache and Hard Reload" things go unexpected:
- OidcKeepAliveServiceWorker.json request is failed
![image](https://user-images.githubusercontent.com/8142668/229451533-5ba1485d-a26b-4185-8897-0045d2114168.png)
- It still shows that the user is authenticated
![image](https://user-images.githubusercontent.com/8142668/229451868-6a8632cd-ae87-45f7-a7e0-88387f00acd5.png)
- Which eventually fails all consequent requests 
![image](https://user-images.githubusercontent.com/8142668/229452936-cca66bf2-65a3-49ba-9afb-54a07152cd84.png)

#### Expected
OidcKeepAliveServiceWorker.json requests should not fail, but if they have to - it should be visible to callers anyhow

#### Actual
OidcKeepAliveServiceWorker.json cascade fails all consequent requests
If I refresh the page again without "Empty Cache and Hard Reload" it works as if nothing happened

**Comment by guillaume-chervet** [comment]
hi @Zamaletdinov , thank you for your issue.

OidcKeepAliveServiceWorker.json requests will not fail in latest version. It is a hack in order to keep alive service worker. The fail is a kind of volontary fail.

The hard refresh that bypass the service worker is a "normal" browser behavior : https://stackoverflow.com/questions/35628243/how-to-prevent-hard-reloads-from-bypassing-the-service-worker

I hope it will be changed one day. I cannot do a lot on that.

**Comment by Zamaletdinov** [comment]
Thank you for your response @guillaume-chervet! Can't wait to see the latest versions :)

**Comment by blackspider73** [comment]
looks like this solution will not work in FF Private mode
